import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import LeadForm from "@/components/LeadForm";
import {
  Arrow,
  Check,
  Container,
  GhostLink,
  Pill,
  PrimaryLink,
  Section,
  SectionHeading,
} from "@/components/ui";
import { accents, courses, getCourse } from "@/lib/courses";
import { site } from "@/lib/site";

export function generateStaticParams() {
  return courses.map((c) => ({ slug: c.slug }));
}

export async function generateMetadata({
  params,
}: PageProps<"/programs/[slug]">): Promise<Metadata> {
  const { slug } = await params;
  const course = getCourse(slug);
  if (!course) return { title: "Programme not found" };

  return {
    title: `${course.title} Course in Bengaluru`,
    description: `${course.summary.slice(0, 155)}…`,
    alternates: { canonical: `/programs/${course.slug}` },
    openGraph: {
      title: `${course.title} — ${site.name}`,
      description: course.tagline,
      url: `${site.url}/programs/${course.slug}`,
      // No `images` key on purpose — the per-programme card generated by
      // ./opengraph-image.tsx is attached automatically for this segment.
    },
  };
}

export default async function CoursePage({
  params,
}: PageProps<"/programs/[slug]">) {
  const { slug } = await params;
  const course = getCourse(slug);
  if (!course) notFound();

  const a = accents[course.accent];
  const others = courses.filter((c) => c.slug !== course.slug).slice(0, 3);

  const courseSchema = {
    "@context": "https://schema.org",
    "@type": "Course",
    name: course.title,
    description: course.summary,
    url: `${site.url}/programs/${course.slug}`,
    courseCode: course.code,
    educationalLevel: course.level,
    teaches: course.outcomes,
    coursePrerequisites: course.prerequisites,
    inLanguage: "en",
    provider: {
      "@type": "EducationalOrganization",
      name: site.legalName,
      url: site.url,
      "@id": `${site.url}/#organization`,
    },
    hasCourseInstance: [
      {
        "@type": "CourseInstance",
        courseMode: ["Onsite", "Online"],
        courseWorkload: course.effort,
        location: {
          "@type": "Place",
          name: site.name,
          address: {
            "@type": "PostalAddress",
            streetAddress: `${site.address.line1}, ${site.address.line2}`,
            addressLocality: site.address.city,
            addressRegion: site.address.state,
            postalCode: site.address.postalCode,
            addressCountry: site.address.country,
          },
        },
      },
    ],
  };

  const facts = [
    { label: "Duration", value: course.duration },
    { label: "Weekly effort", value: course.effort },
    { label: "Level", value: course.level },
    { label: "Format", value: course.format },
    { label: "Mode", value: course.mode },
    { label: "Typical range", value: course.salaryRange },
  ];

  return (
    <>
      <script
        type="application/ld+json"
        suppressHydrationWarning
        dangerouslySetInnerHTML={{ __html: JSON.stringify(courseSchema) }}
      />

      {/* ---------------------------------------------------------------- Hero */}
      <section className="relative overflow-hidden border-b border-white/10">
        <div className="aurora" />
        <div className="absolute inset-0 grid-lines" aria-hidden="true" />

        <Container className="relative z-10 py-16 sm:py-20">
          <nav aria-label="Breadcrumb" className="text-xs text-fg-subtle">
            <Link href="/" className="hover:text-cyan-300">
              Home
            </Link>
            <span className="mx-2">/</span>
            <Link href="/programs" className="hover:text-cyan-300">
              Programmes
            </Link>
            <span className="mx-2">/</span>
            <span className="text-fg-muted">{course.shortTitle}</span>
          </nav>

          <div className="mt-8 grid gap-12 lg:grid-cols-12 lg:gap-16">
            <div className="lg:col-span-7">
              <div className="flex flex-wrap items-center gap-3">
                <span className={`font-mono text-xs tracking-widest ${a.text}`}>
                  {course.code}
                </span>
                <Pill className={a.chip}>{course.level}</Pill>
                <Pill>{course.duration}</Pill>
              </div>

              <h1 className="mt-6 text-4xl font-bold leading-[1.1] sm:text-5xl">
                {course.title}
              </h1>
              <p className={`mt-4 text-lg font-medium ${a.text}`}>
                {course.tagline}
              </p>
              <p className="mt-6 text-base leading-relaxed text-fg-muted">
                {course.summary}
              </p>

              <div className="mt-9 flex flex-col gap-3 sm:flex-row">
                <PrimaryLink href="#apply">
                  Request the syllabus &amp; fees <Arrow />
                </PrimaryLink>
                <a
                  href={`tel:${site.phoneHref}`}
                  className="inline-flex items-center justify-center gap-2 rounded-full border border-white/15 px-6 py-3 text-sm font-semibold text-fg transition-colors hover:border-cyan-400/50 hover:bg-white/5"
                >
                  Call {site.phone}
                </a>
              </div>
            </div>

            <div className="lg:col-span-5">
              <dl className="card grid grid-cols-2 gap-x-6 gap-y-6 p-7">
                {facts.map((f) => (
                  <div key={f.label}>
                    <dt className="text-xs text-fg-subtle">{f.label}</dt>
                    <dd className="mt-1.5 text-sm font-semibold leading-snug text-fg">
                      {f.value}
                    </dd>
                  </div>
                ))}
              </dl>
            </div>
          </div>
        </Container>
      </section>

      {/* ------------------------------------------------------------ Outcomes */}
      <Section>
        <div className="grid gap-14 lg:grid-cols-12 lg:gap-16">
          <div className="lg:col-span-5">
            <SectionHeading
              eyebrow="Outcomes"
              title="What you will be able to do"
              intro="Not topics covered — capabilities you can demonstrate in an interview and on day one of the job."
            />
          </div>
          <ul className="space-y-5 lg:col-span-7">
            {course.outcomes.map((o) => (
              <li key={o} className="flex items-start gap-4">
                <Check className={`mt-0.5 ${a.text}`} />
                <span className="text-base leading-relaxed text-fg-muted">
                  {o}
                </span>
              </li>
            ))}
          </ul>
        </div>
      </Section>

      {/* ----------------------------------------------------------- Curriculum */}
      <Section className="border-y border-white/10 bg-ink-900/40">
        <SectionHeading
          eyebrow="Curriculum"
          title={`${course.modules.length} modules over ${course.duration}`}
          intro="Every module ends in working code that is reviewed by a mentor before you move on."
        />

        <div className="mt-14 space-y-4">
          {course.modules.map((m, i) => (
            <details
              key={m.title}
              open={i === 0}
              className="card group overflow-hidden"
            >
              <summary className="flex cursor-pointer list-none items-center justify-between gap-6 p-6 [&::-webkit-details-marker]:hidden">
                <div className="flex items-start gap-5">
                  <span
                    className={`mt-0.5 font-mono text-sm font-semibold ${a.text}`}
                  >
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <div>
                    <h3 className="text-lg font-bold leading-snug text-fg">
                      {m.title}
                    </h3>
                    <p className="mt-1 font-mono text-[0.6875rem] uppercase tracking-widest text-fg-subtle">
                      {m.duration}
                    </p>
                  </div>
                </div>
                <span
                  aria-hidden="true"
                  className="grid h-6 w-6 shrink-0 place-items-center rounded-full border border-white/20 text-fg-muted transition-transform duration-200 group-open:rotate-45"
                >
                  <svg viewBox="0 0 12 12" className="h-2.5 w-2.5" fill="none">
                    <path
                      d="M6 1v10M1 6h10"
                      stroke="currentColor"
                      strokeWidth="1.6"
                      strokeLinecap="round"
                    />
                  </svg>
                </span>
              </summary>

              <ul className="space-y-3 border-t border-white/10 px-6 py-6 pl-16">
                {m.topics.map((t) => (
                  <li
                    key={t}
                    className="relative pl-5 text-sm leading-relaxed text-fg-muted before:absolute before:left-0 before:top-2.5 before:h-1 before:w-1 before:rounded-full before:bg-current before:opacity-50"
                  >
                    {t}
                  </li>
                ))}
              </ul>
            </details>
          ))}
        </div>
      </Section>

      {/* ------------------------------------------------------------ Capstone */}
      <Section>
        <div className="grid gap-14 lg:grid-cols-12 lg:gap-16">
          <div className="lg:col-span-5">
            <SectionHeading
              eyebrow="Capstone"
              title="What you walk out with"
              intro="Portfolio work substantial enough to carry a technical interview on its own."
            />
          </div>
          <div className="space-y-5 lg:col-span-7">
            {course.capstones.map((c, i) => (
              <div key={c} className="card p-7">
                <span className={`font-mono text-xs tracking-widest ${a.text}`}>
                  PROJECT {String(i + 1).padStart(2, "0")}
                </span>
                <p className="mt-3 text-base leading-relaxed text-fg">{c}</p>
              </div>
            ))}
          </div>
        </div>
      </Section>

      {/* -------------------------------------------------- Tools / roles / fit */}
      <Section className="border-y border-white/10 bg-ink-900/40">
        <div className="grid gap-12 lg:grid-cols-3">
          <div>
            <h2 className="eyebrow">Tools &amp; stack</h2>
            <div className="mt-6 flex flex-wrap gap-2">
              {course.tools.map((t) => (
                <span
                  key={t}
                  className="rounded-lg border border-white/10 bg-white/4 px-3 py-1.5 font-mono text-xs text-fg-muted"
                >
                  {t}
                </span>
              ))}
            </div>
          </div>

          <div>
            <h2 className="eyebrow">Roles this leads to</h2>
            <ul className="mt-6 space-y-3">
              {course.roles.map((r) => (
                <li key={r} className="flex items-center gap-3 text-sm text-fg-muted">
                  <span
                    aria-hidden="true"
                    className={`h-1.5 w-1.5 shrink-0 rounded-full ${a.dot}`}
                  />
                  {r}
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h2 className="eyebrow">Who it is for</h2>
            <ul className="mt-6 space-y-3">
              {course.audience.map((r) => (
                <li key={r} className="text-sm leading-relaxed text-fg-muted">
                  {r}
                </li>
              ))}
            </ul>

            <h2 className="eyebrow mt-8">Prerequisites</h2>
            <ul className="mt-6 space-y-3">
              {course.prerequisites.map((r) => (
                <li key={r} className="text-sm leading-relaxed text-fg-muted">
                  {r}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </Section>

      {/* --------------------------------------------------------------- Apply */}
      <Section id="apply">
        <div className="grid gap-14 lg:grid-cols-2 lg:gap-20">
          <div>
            <SectionHeading
              eyebrow="Enrol"
              title={
                <>
                  Get the full syllabus for{" "}
                  <span className={a.text}>{course.shortTitle}</span>
                </>
              }
              intro="Request the detailed module-by-module syllabus, current batch dates and fee structure. A counsellor will also check whether this is the right programme for your background."
            />
          </div>
          <LeadForm defaultProgram={course.title} />
        </div>
      </Section>

      {/* ---------------------------------------------------------- Other progs */}
      <Section className="border-t border-white/10">
        <SectionHeading eyebrow="Also consider" title="Other programmes" />
        <div className="mt-10 grid gap-6 md:grid-cols-3">
          {others.map((o) => {
            const oa = accents[o.accent];
            return (
              <Link
                key={o.slug}
                href={`/programs/${o.slug}`}
                className="card card-hover group p-6"
              >
                <span className={`font-mono text-[0.6875rem] tracking-widest ${oa.text}`}>
                  {o.code}
                </span>
                <h3 className="mt-3 text-base font-bold">{o.title}</h3>
                <p className="mt-2 text-sm text-fg-muted">{o.tagline}</p>
                <span className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-fg">
                  Details
                  <Arrow className="transition-transform group-hover:translate-x-1" />
                </span>
              </Link>
            );
          })}
        </div>
        <div className="mt-10">
          <GhostLink href="/programs">
            All programmes <Arrow />
          </GhostLink>
        </div>
      </Section>
    </>
  );
}
